
import com.sun.speech.freetts.Voice;
import com.sun.speech.freetts.VoiceManager;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;





/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Huy Duc
 */
public class rundictionary2 extends javax.swing.JFrame {
static  ArrayList <Word> list = new ArrayList<>();
    DefaultListModel wordTargetL= new DefaultListModel(); 
    DefaultListModel wordExplainL = new DefaultListModel();
    DefaultListModel cl = new DefaultListModel();
    Voice v;
    VoiceManager vm;
   static ArrayList<Word> lists=new ArrayList<>();
    //
static public ArrayList insertFromFile(){
        try(BufferedReader br = new BufferedReader (new FileReader("Dictionarise.txt"))){
             String currentLine; 
             while((currentLine=br.readLine())!=null){
                 Word word = new Word(null, null);
                 String[] splitString;
                 splitString = currentLine.split("\t");
                 word.word_target = splitString[0];
                 word.word_explain = splitString[1];
                 list.add(word);
              }
             
         }catch(IOException e){
                     e.printStackTrace();
                     }
        Collections.sort(list);
        return list;
    }
    //private Object wordTargetList;
    ///
    private void searchFill(String searchTerm){
       DefaultListModel defaultMode = new DefaultListModel(); 
       if( !searchTerm.equals(null)){
        for(int i=0; i<list.size(); i++){
            String startname = list.get(i).word_target.toString().toLowerCase();
            if(startname.contains(searchTerm.toLowerCase())){
                defaultMode.addElement(list.get(i).word_target);
            }
        }
        wordTargetL = defaultMode;
               wordTargetList.setModel(wordTargetL);
        
    }
    else{
    loaddata(list);
}}
    

 void loaddata(ArrayList <Word> list) {
        int i;
        for( i=0; i<list.size(); i++){
            wordTargetList.setModel(wordTargetL);
            wordTargetL.addElement(list.get(i).word_target);
        }
         
    }
 ///
 
 

    /**
     * Creates new form rundictionary2
     */
    public rundictionary2() {
        initComponents();
        insertFromFile();
        loaddata(list);
       jPanel6.setVisible(false);
       jPanel8.setVisible(true);
       jPanel5.setVisible(false);
       jPanel9.setVisible(true);
       jPanel2.setVisible(true);
       jPanel6.setVisible(false);
       

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        okEditButton = new javax.swing.JButton();
        clearEditButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        vietEditArea = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        cancelEditButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        engEditArea = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        wordExplainArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        okAddButton = new javax.swing.JButton();
        clearAddButton = new javax.swing.JButton();
        cancelAddButtion = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        engAddArea = new javax.swing.JTextField();
        vietAddArea = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        findButton = new javax.swing.JButton();
        speakButton = new javax.swing.JButton();
        addButton = new javax.swing.JButton();
        editbutton = new javax.swing.JButton();
        delebutton = new javax.swing.JButton();
        historyButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        textFind = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        wordTargetList = new javax.swing.JList<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DICTIONARY - ENGLISH-VIETNAMESE");

        jLayeredPane1.setForeground(new java.awt.Color(51, 51, 255));
        jLayeredPane1.setToolTipText("tudien");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setForeground(new java.awt.Color(102, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        okEditButton.setText("OK");
        okEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okEditButtonActionPerformed(evt);
            }
        });
        jPanel5.add(okEditButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 200, 70, -1));

        clearEditButton.setText("Clear");
        clearEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearEditButtonActionPerformed(evt);
            }
        });
        jPanel5.add(clearEditButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 200, 70, -1));

        vietEditArea.setColumns(20);
        vietEditArea.setRows(5);
        jScrollPane2.setViewportView(vietEditArea);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 126, 347, 56));

        jLabel5.setText("Vietnamese: ");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 140, -1, -1));

        cancelEditButton.setText("Cancel");
        cancelEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelEditButtonActionPerformed(evt);
            }
        });
        jPanel5.add(cancelEditButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(376, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("EDIT A WORD");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 38, -1, -1));

        jLabel4.setText("English:");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 82, -1, -1));

        engEditArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engEditAreaActionPerformed(evt);
            }
        });
        jPanel5.add(engEditArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 73, 347, 32));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 22, -1, 270));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        wordExplainArea.setEditable(false);
        wordExplainArea.setColumns(20);
        wordExplainArea.setRows(5);
        wordExplainArea.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.add(wordExplainArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 530, 390));

        jButton1.setText("jButton1");
        jPanel8.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 370, -1, -1));

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 530, 410));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("English:");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Vietnamese:");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        okAddButton.setText("OK");
        okAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okAddButtonActionPerformed(evt);
            }
        });
        jPanel6.add(okAddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 77, -1));

        clearAddButton.setText("Clear");
        clearAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearAddButtonActionPerformed(evt);
            }
        });
        jPanel6.add(clearAddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 77, -1));

        cancelAddButtion.setText("Cancel");
        cancelAddButtion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelAddButtionActionPerformed(evt);
            }
        });
        jPanel6.add(cancelAddButtion, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 77, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("ADD A NEW WORD ");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));
        jPanel6.add(engAddArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 240, 30));
        jPanel6.add(vietAddArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 240, 30));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 42, 431, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        findButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        findButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                findButtonMouseClicked(evt);
            }
        });
        findButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findButtonActionPerformed(evt);
            }
        });
        jPanel9.add(findButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        speakButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/speaker.png"))); // NOI18N
        speakButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speakButtonActionPerformed(evt);
            }
        });
        jPanel9.add(speakButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 0, 50, -1));

        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-ADD-16.png"))); // NOI18N
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });
        jPanel9.add(addButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, -1));

        editbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-compose-16.png"))); // NOI18N
        editbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbuttonActionPerformed(evt);
            }
        });
        jPanel9.add(editbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 40, -1));

        delebutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-TRASH-16.png"))); // NOI18N
        delebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delebuttonActionPerformed(evt);
            }
        });
        jPanel9.add(delebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 40, -1));

        historyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-save-as-16.png"))); // NOI18N
        historyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historyButtonActionPerformed(evt);
            }
        });
        jPanel9.add(historyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 0, 39, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-clear-symbol-16.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 50, -1));

        textFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFindActionPerformed(evt);
            }
        });
        textFind.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFindKeyReleased(evt);
            }
        });

        wordTargetList.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        wordTargetList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wordTargetListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(wordTargetList);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 255));
        jLabel7.setText("DICTONARY");
        jLabel7.setOpaque(true);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("English - VietNamese ");

        jLayeredPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(textFind, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9))
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jLayeredPane1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(textFind)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)))
                .addGap(5, 5, 5)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel8)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)))
                .addGap(11, 11, 11)
                .addComponent(textFind, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        jPanel6.setVisible(true);
        jPanel8.setVisible(false);
        jPanel5.setVisible(false);
    }//GEN-LAST:event_addButtonActionPerformed

    private void cancelAddButtionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelAddButtionActionPerformed
    jPanel6.setVisible(false);
    engAddArea.setText(null);
    vietAddArea.setText(null);
    jPanel8.setVisible(true);
    jPanel5.setVisible(false);
    }//GEN-LAST:event_cancelAddButtionActionPerformed
//Nut dong Panle cua ADD
    private void clearAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearAddButtonActionPerformed
    engAddArea.setText(null);
    vietAddArea.setText(null);
        
    }//GEN-LAST:event_clearAddButtonActionPerformed
//Nut ok cuav ADD
    boolean checksameword ( String a){
     
        return dictionaryLookup(list, a) == null;
        
    }
    
    
    private void okAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okAddButtonActionPerformed
            String a = engAddArea.getText();
           if(a.compareTo("")==0||vietAddArea.getText().compareTo("")==0){
             JOptionPane.showMessageDialog(null, "Invalid Adding!");
           }
        else
        {   
            Word newWord = new Word(engAddArea.getText(), vietAddArea.getText());
            if(dictionaryLookup(list, a)==null){
            list.add(newWord);
            
            Collections.sort(list);
            wordTargetList.setModel(wordTargetL);
            wordTargetL.removeAllElements();
            loaddata(list);
            JOptionPane.showMessageDialog(null, "Done!");
            }
            else{
                JOptionPane.showMessageDialog(null, "Invalid Adding!");
            }
        }    
    }//GEN-LAST:event_okAddButtonActionPerformed
 
//Click vao item cua List de lay du lieu
    private void wordTargetListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wordTargetListMouseClicked

        if(!wordTargetL.isEmpty()&& wordTargetList.getSelectedIndex()>=0){
            String aaa = dictionaryLookup ( list, wordTargetList.getSelectedValue());
            wordExplainArea.setText(aaa);
            textFind.setText(wordTargetList.getSelectedValue());
            vietEditArea.setText(aaa);
            
        }
 engEditArea.setText(wordTargetList.getSelectedValue());
    
        // TODO add your handling code here:
    }//GEN-LAST:event_wordTargetListMouseClicked
//Nut tim kiem
    private void findButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_findButtonMouseClicked

if(!textFind.getText().equals("")){

            if(dictionaryLookup( list, textFind.getText())!=null){
                wordExplainArea.setText(dictionaryLookup( list,textFind.getText()));

            }
            else{
                wordExplainArea.setText("Không tìm thấy từ.");
            }
}        // TODO add your handling code here:
    }//GEN-LAST:event_findButtonMouseClicked
//goi y tu khi tim kiem
    private void textFindKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFindKeyReleased
        searchFill(textFind.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_textFindKeyReleased
//Tim kiem bang hop tim kiem
    private void textFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFindActionPerformed
        if(!textFind.getText().equals("")){

            if(dictionaryLookup( list, textFind.getText())!=null){
                wordExplainArea.setText(dictionaryLookup( list, textFind.getText()));
            }
            else{
                wordExplainArea.setText("Không tìm thấy từ.");
            }}
            else{
            //loaddata(list);
                wordExplainArea.setText(null);
            }
        
    }//GEN-LAST:event_textFindActionPerformed
//Phat am
    private void speakButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speakButtonActionPerformed
        System.setProperty("mbrola.base", "mbrola");
        VoiceManager vm = VoiceManager.getInstance();
        v=vm.getVoice("mbrola_us1");
        v.allocate();
        v.speak(textFind.getText());
        // TODO add your handling code here:
    }//GEN-LAST:event_speakButtonActionPerformed
//Nut mo hop EDIT
    private void editbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbuttonActionPerformed
    jPanel5.setVisible(true);
    jPanel8.setVisible(false);
    jPanel6.setVisible(false);
    
    engEditArea.setText(wordTargetList.getSelectedValue());
    wordExplainArea.setText(vietEditArea.getText());
// TODO add your handling code here:
    }//GEN-LAST:event_editbuttonActionPerformed
//Dong EDit
    private void cancelEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelEditButtonActionPerformed
        jPanel5.setVisible(false);
        engEditArea.setText(null);
        vietEditArea.setText(null);
        jPanel8.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelEditButtonActionPerformed
//Xoa du lieu hop edit
    private void clearEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearEditButtonActionPerformed
        engEditArea.setText(null);
        vietEditArea.setText(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_clearEditButtonActionPerformed
//OK cua edit
    private void okEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okEditButtonActionPerformed
        // TODO add your handling code here:
        Word word= new Word(null, null);
        int i, k = 0;
        if(!wordTargetL.isEmpty()&& wordTargetList.getSelectedIndex()>=0){
//            word.word_target = engEditArea.getText();
//            word.word_explain = vietEditArea.getText();
//            for(i=0; i<list.size(); i++){
//                if(wordTargetList.getSelectedValue().equals(list.get(i).word_target)){
//                    
//                }
//            }
    k= dictionaryLookups(list,wordTargetList.getSelectedValue());
 JOptionPane.showMessageDialog(null, "You have edited successfull.");
           // list.remove(k);
           // list.add(word);
           list.get(k).setword_explain(vietEditArea.getText());
            wordTargetList.setModel(wordTargetL);
            wordTargetL.removeAllElements();
            loaddata(list);
            
        }
        else {
            JOptionPane.showMessageDialog(null, "Invalid editng!");
        }
    }//GEN-LAST:event_okEditButtonActionPerformed

    private void engEditAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_engEditAreaActionPerformed
        
        engEditArea.setText(wordTargetList.getSelectedValue());
        // TODO add your handling code here:
    }//GEN-LAST:event_engEditAreaActionPerformed
//Xoa 1 ham
    private void delebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delebuttonActionPerformed
        int click = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete that word?","Confirm delete", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(!wordTargetL.isEmpty()&& wordTargetList.getSelectedIndex()>=0){
        if(click == JOptionPane.YES_OPTION){
        int index=-1;    
        textFind.setText(null);
        wordExplainArea.setText(null);
        
       for(int i =0; i<list.size(); i++){
        if(engEditArea.getText().equals(list.get(i).word_target)){
            index = i;
            break;
        }
      }
        list.remove(index); 
        //wordTargetList.setModel(wordTargetL);
        //wordTargetL.removeAllElements();
       wordTargetL.removeElementAt(wordTargetList.getSelectedIndex());
       JOptionPane.showMessageDialog(null, "You have deleted a word.");
        }}
        else
        {
            JOptionPane.showMessageDialog(null, "Let choose word you want to delete!");
        }
         //loaddata(list);
        
        //wordTargetL.removeElementAt(wordTargetList.getSelectedIndex());
        
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_delebuttonActionPerformed
    

    private void findButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findButtonActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_findButtonActionPerformed

    private void historyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyButtonActionPerformed
int click = JOptionPane.showConfirmDialog(null, "Are you sure you want to SAVE in source??","Confirm delete", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
       if(click==JOptionPane.YES_OPTION) {    try {
                    ghiLaivofile();        // TODO add your handling code here:
                } catch (IOException ex) {
                    Logger.getLogger(rundictionary2.class.getName()).log(Level.SEVERE, null, ex);
                }
       }
       
    }//GEN-LAST:event_historyButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        textFind.setText("");
        wordExplainArea.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed
 
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rundictionary2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rundictionary2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rundictionary2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rundictionary2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rundictionary2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton addButton;
    private javax.swing.JButton cancelAddButtion;
    private javax.swing.JButton cancelEditButton;
    public javax.swing.JButton clearAddButton;
    private javax.swing.JButton clearEditButton;
    public javax.swing.JButton delebutton;
    private javax.swing.JButton editbutton;
    private javax.swing.JTextField engAddArea;
    private javax.swing.JTextField engEditArea;
    private javax.swing.JButton findButton;
    public javax.swing.JButton historyButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JButton okAddButton;
    private javax.swing.JButton okEditButton;
    private javax.swing.JButton speakButton;
    private javax.swing.JTextField textFind;
    private javax.swing.JTextField vietAddArea;
    private javax.swing.JTextArea vietEditArea;
    private javax.swing.JTextArea wordExplainArea;
    private javax.swing.JList<String> wordTargetList;
    // End of variables declaration//GEN-END:variables
 

 public String dictionaryLookup(ArrayList<Word> list,String tim) {//tiem kiem tu
            int k=0,l=0;
            int a=0;
            int b=list.size();  
            String serch=null ;
            
        do{
            int i=(a+b)/2;
           int s=tim.compareTo(list.get(i).word_target);
           if(s==0){
               serch=list.get(i).word_explain;
               k=1;
           }
           else if(s>0)a=i+1;
           else if(s<0)b=i-1;
           
        }while(k!=1&&a<=b);
        if(k==0)serch=null;
        return serch;
    } 
    public int dictionaryLookups(ArrayList<Word> list,String tim) {//tiem kiem tu
            int k=0,l=0;
            int a=0;
            int b=list.size();  
            String serch=null ;
            int i;
        do{
           i=(a+b)/2;
           int s=tim.compareTo(list.get(i).word_target);
           if(s==0){
               k=1;
           }
           else if(s>0)a=i+1;
           else if(s<0)b=i-1;
           
        }while(k!=1&&a<=b);
        return i;
    }  
///
 //add a new word in a list and load on wordTargetList.

void ghiLaivofile() throws IOException{
try (BufferedWriter bw = new BufferedWriter(new FileWriter("Dictionarise.txt"))) {
			for(int i=0; i<list.size(); i++){
                            String currentLine= list.get(i).word_target +"\t"+list.get(i).word_explain+"\n";
                            bw.write(currentLine);
                        }
			// không cần đóng BufferedWriter (nó đã tự động đóng)
			// bw.close();
			
		} catch (IOException e) {
			e.printStackTrace();
		}
	}



////
}
